"""Add meetings

Revision ID: d0e7dd90d5e0
Revises: d4e5f6g7h8i9
Create Date: 2026-09-15 20:06:22.367363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0e7dd90d5e0'
down_revision: Union[str, None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('meetings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('meetings', sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('meetings', sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('meetings', sa.Column('created_by', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_meetings_creator_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_column('meetings', 'description')
    op.drop_column('meetings', 'report_content')
    op.drop_column('meetings', 'scheduled_at')
    op.drop_column('meetings', 'participant_ids')
    op.drop_column('meetings', 'creator_id')
    op.drop_column('meetings', 'reminder_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('creator_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('report_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('meetings', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_meetings_creator_id'), 'meetings', ['creator_id'], unique=False)
    op.drop_column('meetings', 'created_by')
    op.drop_column('meetings', 'report')
    op.drop_column('meetings', 'participants')
    op.drop_column('meetings', 'end_time')
    op.drop_column('meetings', 'start_time')
    # ### end Alembic commands ###
